Update ddev.yml to fail when quickstart fails
* ddev quick-start is set up to not fail when one of its component scripts, like drush site-install fails
* This change addresses this by forcing an error code on the quick-start script when of of its components fail

diff --git a/.github/workflows/ddev.yml b/.github/workflows/ddev.yml
--- a/.github/workflows/ddev.yml
+++ b/.github/workflows/ddev.yml
@@ -33,7 +33,12 @@ jobs:
 
       - name: Install Starshot
         run: |
-          ddev quick-start
+          OUTPUT=$(ddev quick-start 2>&1)
+          echo "$OUTPUT"
+          if echo "$OUTPUT" | grep -q "returned with error code 1"; then
+            echo "Starshot installation failed"
+            exit 1
+          fi
 
       - name: Confirm that Starshot is running
         run: |
